fix for #4 and #13 + small things
CottonMC/UniversalComponents pull request #14
Opened 2020-09-02 20:46 UTC by Albert-Einholz

fix for #4 and #13 + small things like removing some unused imports

2020-09-02 21:02 UTC, UpcraftLP requested changes

2020-09-02 21:02 UTC, UpcraftLP commented on src/main/java/io/github/cottonmc/component/data/impl/SimpleUnit.java
> +		FORMAT_STANDARD.setMinimumFractionDigits(2);
I don't think we should *always* force 2 digits.

2020-09-02 21:23 UTC, LemmaEOF commented on src/main/java/io/github/cottonmc/component/data/impl/SimpleUnit.java
> +		FORMAT_STANDARD.setMinimumFractionDigits(2);
This is to fix #4 - check the video they link on the issue. I'm not a *hundred* percent happy with this, to be honest.

2020-09-02 21:28 UTC, Boundarybreaker approved these changes

2020-09-08 07:35 UTC, UpcraftLP approved these changes
Aight, guess we can merge this anyway, and if we need a different way to format we can add that later.

2020-09-11 14:43 UTC, Albert-Einholz commented
so will somebody merge this?

2020-09-11 14:44 UTC, UpcraftLP commented
no

2020-09-11 14:44 UTC, merged